<?php

namespace App\Enum;

enum SpatieUserPermissionEnum: string
{
    case PERMISSION_FULL = "PERMISSION_FULL";

    case PERMISSION_UNIVERSITY_UPDATE = "PERMISSION_UNIVERSITY_UPDATE";
    case PERMISSION_UNIVERSITY_SHOW = "PERMISSION_UNIVERSITY_SHOW";
    case PERMISSION_UNIVERSITY_COLLECTION = "PERMISSION_UNIVERSITY_COLLECTION";

    case PERMISSION_FACULTY_UPDATE = "PERMISSION_FACULTY_UPDATE";
    case PERMISSION_FACULTY_SHOW = "PERMISSION_FACULTY_SHOW";
    case PERMISSION_FACULTY_COLLECTION = "PERMISSION_FACULTY_COLLECTION";

    case PERMISSION_DEPARTMENT_UPDATE = "PERMISSION_DEPARTMENT_UPDATE";
    case PERMISSION_DEPARTMENT_SHOW = "PERMISSION_DEPARTMENT_SHOW";
    case PERMISSION_DEPARTMENT_CREATE = "PERMISSION_DEPARTMENT_CREATE";
    case PERMISSION_DEPARTMENT_DELETE = "PERMISSION_DEPARTMENT_DELETE";
    case PERMISSION_DEPARTMENT_COLLECTION = "PERMISSION_DEPARTMENT_COLLECTION";

    case PERMISSION_OPTION_UPDATE = "PERMISSION_OPTION_UPDATE";
    case PERMISSION_OPTION_SHOW = "PERMISSION_OPTION_SHOW";
    case PERMISSION_OPTION_CREATE = "PERMISSION_OPTION_CREATE";
    case PERMISSION_OPTION_DELETE = "PERMISSION_OPTION_DELETE";
    case PERMISSION_OPTION_COLLECTION = "PERMISSION_OPTION_COLLECTION";
}
